### ISSUE TITLE
Installation via brew

### ISSUE THREAD

**Issue by ilyar** [P3GLEG/Whaler#11]
Maybe I have old habits ...

See the installation via [brew](http://brew.sh/) (The Missing Package Manager for macOS, Linux and Windows 10):

```
brew tap ilyar/software
brew install whaler
```

or 

```
brew install ilyar/software/whaler
```

Source https://github.com/ilyar/homebrew-software/blob/main/Formula/whaler.rb
More about аormula see on https://docs.brew.sh/Formula-Cookbook

**Comment by P3GLEG** [comment]
I quickly read over the code found at https://github.com/ilyar/homebrew-software/blob/69f57ea7cd12eda4ef7d53fc1e4c86f99f5e911a/Formula/whaler.rb It pulls from my main repository and doesn't look malicious. 

I haven't had a chance to do this myself, so if anyone wants to use this way go for it. 

I'd recommend just using Docker to inspect docker images and mounting it with a read only socket

```
docker pull pegleg/whaler
docker run -t --rm -v /var/run/docker.sock:/var/run/docker.sock:ro pegleg/whaler -sV=1.36 nginx:latest
```
