### ISSUE TITLE
Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40

### ISSUE THREAD

**Issue by eva-barczykowska** [P3GLEG/Whaler#8]
My version of client is 1.40 but I get an the following error after trying to execute the command:
./Whaler nginx:latest -f

Error response from daemon: client version 1.41 is too new. Maximum supported API [version]([url](url)) is 1.40
![whaler_max_supported_api](https://user-images.githubusercontent.com/21038539/73478820-12a2c000-4397-11ea-9418-27c77634f462.PNG)
I''m not sure if this qualifies as a bug. Can you have a look?

**Comment by P3GLEG** [comment]
Can you try specify the version `-sV=1.40` and send me the output

**Comment by eva-barczykowska** [comment]
![whaler_sV140](https://user-images.githubusercontent.com/21038539/73520035-e9b81480-4402-11ea-9fc8-5e8f0f5c1e44.PNG)

**Comment by P3GLEG** [comment]
That's strange behavior. Let me try and replicate the scenario and debug it tomorrow. I think off the top of my head is the Docker SDK built into your Whaler is causing it to be 1.41. If you can pin the docker go package to a lower version it should work. My understanding reading the documentation suggests that it should still be able to communicate with the server though.

**Comment by P3GLEG** [comment]
I had the same error occur on Ubuntu, but was able to set the version to one before no problem. 

![image (7)](https://user-images.githubusercontent.com/25095513/74774729-1a90aa00-5249-11ea-8994-f20acf5081cd.png)

Are you still experiencing the issue? It may be a Windows problem.
